# Generated by Django 4.1.7 on 2023-03-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliateapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='This is an awesomeproduct'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
