# Generated by Django 4.1.7 on 2023-05-04 19:20

import datetime
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('affiliateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerquery',
            options={'verbose_name_plural': 'Customer queries'},
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_keywords',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_tab_title',
            field=models.CharField(default='title', max_length=255),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_url',
            field=models.TextField(default='blog-url'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='image-link', storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='service',
            name='service_description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_keywords',
            field=models.TextField(default='keywords'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_tab_title',
            field=models.CharField(default='title', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='service_url',
            field=models.TextField(default='service-url'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 19, 20, 11, 94451)),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=''),
        ),
    ]
